# Specify a base image
FROM node:20 AS build 

# Change working directory
WORKDIR /usr/app

# Copy in the app and weights
COPY ./ /usr/app

# Install dependencies
RUN yarn global add turbo
RUN yarn install
RUN turbo build

EXPOSE 3050

CMD turbo start --filter='./apps/brew-careers'